-- Initialisation MySQL pour mvc-allocine
CREATE DATABASE IF NOT EXISTS allocine DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE allocine;

CREATE TABLE IF NOT EXISTS film (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  date_sortie DATE NULL,
  genre VARCHAR(100) NULL,
  auteur VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS diffusion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  film_id INT NOT NULL,
  date_diffusion DATETIME NULL,
  FOREIGN KEY (film_id) REFERENCES film(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
